import { formatFileSize, formatNote, formatThaiDate, isImageAttachment } from "@/lib/format";
import type { WorkLog } from "@/lib/types";
import { getWorkload } from "@/lib/workload-data";

type Props = { date: string; logs: WorkLog[]; onEdit: (log: WorkLog) => void; onDelete: (id: string) => void };

export function DailyLog({ date, logs, onEdit, onDelete }: Props) {
  return (
    <section aria-labelledby="daily-log-title">
      <div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--gold)]">สมุดบันทึก</p><h2 id="daily-log-title" className="mt-1 text-xl font-semibold tracking-tight">งานของวันที่เลือก</h2></div><span className="text-right text-xs text-[var(--muted)]">{formatThaiDate(date)}</span></div>
      {logs.length === 0 ? <div className="paper-grid rounded-2xl border border-dashed border-[#c5cad5] px-5 py-14 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e9edf9] text-xl text-[var(--blue)]">✦</div><h3 className="mt-4 font-semibold">ยังไม่มีบันทึกของวันนี้</h3><p className="mx-auto mt-1 max-w-xs text-sm leading-6 text-[var(--muted)]">เลือกงานจากตารางด้านบน แล้วเพิ่มรายละเอียดการทำงาน</p></div> : <div className="overflow-hidden rounded-2xl border border-[var(--line)] bg-white shadow-[0_8px_22px_rgba(23,35,63,.04)]"><div className="overflow-x-auto"><table className="w-full min-w-[780px] border-collapse text-left text-sm"><caption className="sr-only">ตารางงานที่ทำของวันที่ {formatThaiDate(date)}</caption><thead className="bg-[#eef1f8] text-xs font-bold text-[var(--muted)]"><tr><th className="px-4 py-3.5">หัวข้องาน</th><th className="px-4 py-3.5">รายละเอียดการทำงาน</th><th className="px-4 py-3.5">หมายเหตุ</th><th className="px-4 py-3.5">ไฟล์แนบ</th><th className="px-4 py-3.5">จัดการ</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{logs.map((log) => { const workload = getWorkload(log.workloadId); if (!workload) return null; return <tr key={log.id} className="align-top transition hover:bg-[#fbfcff]"><td className="w-[25%] px-4 py-4"><div className="flex items-center gap-2"><span className="rounded-full bg-[#edf1ff] px-2 py-1 text-xs font-bold text-[var(--blue)]">{workload.code}</span><span className="text-xs text-[var(--muted)]">{workload.category}</span></div><p className="mt-2 font-semibold leading-6">{workload.title}</p></td><td className="w-[29%] whitespace-pre-wrap px-4 py-4 leading-6 text-[#4e5769]">{log.detail}</td><td className="w-[21%] whitespace-pre-wrap px-4 py-4 leading-6 text-[#4e5769]">{formatNote(log.notes ?? "")}</td><td className="w-[15%] px-4 py-4">{log.attachments.length ? <div className="space-y-2">{log.attachments.map((file) => <a key={file.id} href={file.dataUrl} download={file.name} className="focus-ring block max-w-[150px] rounded-lg bg-[#f3f5f9] px-2.5 py-2 text-xs text-[var(--ink)] hover:bg-[#e9edf7]" title={file.name}>{isImageAttachment(file.type) ? <img src={file.dataUrl} alt={`ตัวอย่าง ${file.name}`} className="mb-2 h-16 w-24 rounded-md object-cover" /> : null}<span className="block truncate">{file.name}</span><span className="text-[var(--muted)]">{formatFileSize(file.size)}</span></a>)}</div> : <span className="text-xs text-[var(--muted)]">—</span>}</td><td className="w-[10%] px-4 py-4"><div className="flex flex-col items-start gap-1"><button type="button" onClick={() => onEdit(log)} className="focus-ring rounded-lg px-2 py-1.5 text-xs font-semibold text-[var(--blue)] hover:bg-[#eef1ff]">แก้ไข</button><button type="button" onClick={() => onDelete(log.id)} className="focus-ring rounded-lg px-2 py-1.5 text-xs font-semibold text-[var(--red)] hover:bg-[#fff1f1]">ลบ</button></div></td></tr>})}</tbody></table></div></div>}
    </section>
  );
}
